branches:
  except:
  - master
language: node_js
node_js:
- node
pre_install:
- ulimit -n 8192
install:
- echo "Building for tests"
- yarn run build:test
script:
- echo "Starting tests"
- yarn run test
after_success:
- echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
env:
  global:
  - secure: ZsWSKo3PgUg60w5pkwgyPizRx1UCyw68uvu9NEfJTkSAkA0glZ4V69zw0J/HJKwQ3PUSpjgBNlQoGKodTWEG/2dHJvJ5Aa1lsrcomokIpivThE9OP9XqSGIjozgS764KUNB2OAhknW6d0pgLkcSNN9geisTxFU7W6SYf/tSS7hLYR/E9A4wi3h9jYl7AiUMx+ZRNP5pbtk8mu3zoqfnhd1ieVV4akklvBhh19Ds/8OoRhUByTdxb5hXAgog2AgKuPiQSreJr2bZHg7Lf58h8yXg2TwCHDPRqIi282Ni6zzLQYk2p2UxHKwnyxcY2uY6eicqU5LSbL+8Q6bv37JecWSLPJFenLb9r4LQsBP4uy2npDM4CDw1QxzQ/PfQLIXRfzarCH2xx9Y52b8k4YHBfIAgbRM5XRO5GN2WSmT93E1P8GHcYrwF6V5hMG9V0W62fby78U+Iq97wyJa7s0Jgi+oNdOLRov2j7dXAFN6uQbluePXCbxwL8IC0RMWyg4q0x5mYlswmNZHrUVzvRez0kZ2o75ZeZ7ocI0QAI07Jx/YfhOvwe8Wwcel6cR7odUJZwGYQkNSGee03HeS8Ppxl/3fKjRyGJtwgZNAnGORplbS64dG0zC06+AzQfemAZ1ck89J3eeeC4xKbHYcBNihA7oxKtYbp6E9diFgG2MTjECqg=
  - secure: qHHnFwOLqOV1RQwd6tY1J1icrfwoevxXMDv0avX+kIrL1WGQSSHHiUD61SSyDe5HWLJ6s3Stk/LfCaO9+4fDTwetzZP8NIPk1LMDX0X8eZWORUVG9KT/ffm0gcQerd6dNxMKOUW3Ig1Kl0NmyJ+Vu2o8TNdv+OVUmvUSdhDNmwamzXWsePRhIUZ6IlOMDLZHPdLI6PElIRWUnZSixfaqlON/v0huohHAUTXspO7zyAM/oIcUEjQ6Rpn7i4vYb5+sEZpo+AleaY0MS23fld1siW1R9yZF/gh6bVBqnXC+LKGtNr2DwM4c6WKAZYNxZCLIkU/xccBsHM3TNN4qxIoEgXI+inOkpgotClbi8+n/t9t+jNmBp6TYcBO4HhI7WT8B/5EVp/euiaGkM/lb5CTgWig8Tatf7YgqDdODtfu5eOXSANDFa8mPfG8c8L9giWyclgFq2p4xGrSdheoU3UgpMgRK/zeLL6BFdVdDDK1xoyz0J86zq2Wj21a5sbJvhrAorrt8wbUIKBxvhcrsAYqiCsZmxdSJ4xT+j1y1qYTO7t5UmAytiVIFNYAVRbt9++Rx6uQ1ji+fsCoubnQi8qqL5Q0EIY4MwHncIAyMNgpw9z/BGVwKrorq4qs8MOyEC6za8zLcnoj49xwV6dFsEMibKady/fE1Ch991/5Dx8D96H8=
