branches:
  except:
  - master
language: node_js
node_js:
- node
pre_install:
- ulimit -n 8192
install:
- echo "Building for tests"
- yarn run build:test
script:
- echo "Starting tests"
- yarn run test
after_success:
- echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
env:
  global:
  - secure: fStIlx/I9fi51lOGMvuJ6x/LKn29lf4JbEHHrywksu8Wd1zkDl/hNDsSQ5XhljWHNZtHkjyVaUu+qV8+MGi5LmNBE4DMiG3i8LozczABzEYzuPIUOEO7rWLbJ3S1+MS42qG9vbO3iS6l3HxGtetDLrBHmP+IbTc+IswWxbuTZVTx8OfBFQlRtjZTYxN+1V85+qzb4bPV6HgIO3IzUlyx9iwGcEq4M/lyagjrSKD6kMLDzKnlZDC2FSkXsLNOLJuUMBRiK4ULPriRY3moGDgWkXCtbefDvxaAvqQE+x9ZEK2C3cUDQEtLaoVJ790VkYo6K7GU2iGXwlWIsLOKYD3bgOJjlP8xNjbOzvD22HXSpwMG9RlkOTSKBjo3R/AOfwedRyNpt0hYZwWcCtfzpVZqnm3CVbt9QUTJSzpHj6AgriOGtFNwAMIAAwgoR3V7btNMjovdESubBVVEbUFGupNJUUm2QAL/kmbDNNT5p0Ss73umXt3hZK8+DI8ZfcpMI/SGy+wBpjzsZJJ/woVzkXhXl2JEroNYbPBhmHVt0I9SXlgokngxj4s430MYTPxRVdCpYnDMsOfOWNYd5coW79bXpt8UIP0KWpf1wNAIwa5PMqF3dNQT8EmsYMyMICkJXeNUmL9Sss+WQDkDt5SBu5AzaEnINEh+cQIpunXBQwUuyyA=
  - secure: cZJqY7mBmGKyODQrEEnWysGVxF6sXxFtW7f95F5jOZuvb880pjedNfJSv9qIMKGqyWoKF7hlCk5b3KTQq/ez9s4w+FiFqApP1c8y5S0SEqFpZh+WujeBUNwudCzxX6aYq0UH0KAeko5LVIFoci6MPVmkAO/vMhO8ziDWCg4q9hWK7JAWtBDIY4ceJpVwG+L7hi2EJfhC6yPyDJHVkGNfaWFzeUqk89+BpEc+VIuQ5VvN612S2VDYeVF5SX5mimD8teYza13oR8Dr7ZtnTWuf9gCGL3q+djEdIkcw6Plx8cJSlidxSreQnqgICdhR6jSXP3X/0n/DVA7fCKXDBd0u5NSS6QgNhslid8tMjK7NhBUY6EKCOH8kmdAurR7D/7P/STQgc6YakuOCvqshgTx53q7pSfPBC2jKJ9mJ91zM2kTvToX3UyJRDKeLk2xltfM9Gns+yCj0tC0CVXiMCDGq8UCmgWtPX5HsdqHW8V+LmMsUuraaxJvAbaUzpenuRE5T0ugrb5wDcqSyH80nXa4pizPveDyA9Yc3bqpyyyxOTu8FI+s9aNLZHyVizHi0tWyFyTlpEyAd/mVymgPwTVmB6dg1ggy+THlL9FhX2uYzlZX+bJQsn2WipffbFTkblOC5c2Ux9N29aSBQDyxPzegyphIPHQoABsVrFHu04ahbJ98=
